import { test, expect } from '@fixtures/booking.fixture';

// Import test data builder for creating booking payloads.
import { buildBooking } from '@testdata/booking.data';
import { createLogger } from '@utils/logger';

// Create logger for this test file.
const log = createLogger('booking-crud');

// serial = tests run one after another in the same order.
// This is required because update/delete depend on bookingId created in test 1.
test.describe.serial('@e2e @P0 Level 3 - Booking lifecycle (token from fixture)', () => {

    // Stores booking ID created in the first test.
    let bookingId: number;

    // ============================================================
    // CREATE BOOKING
    // ============================================================

    test('create a booking', async ({ bookingApi }, testInfo) => {

        // Create booking payload using test-data builder.
        const payload = buildBooking({ firstname: 'E2E', lastname: 'Journey' });

        await test.step('POST /booking with a generated payload', async () => {

            // Log booking creation.
            log.info(`Step 1: creating booking for ${payload.firstname} ${payload.lastname}`);

            // Call POST /booking through BookingApi.
            const { bookingid, booking } = await bookingApi.createBooking(payload);

            // Log generated booking ID.
            log.info(`Step 1: created booking id ${bookingid}`);

            // Verify booking ID is valid.
            expect(bookingid).toBeGreaterThan(0);

            // Verify booking firstname.
            expect(booking.firstname).toBe('E2E');

            // Store ID for update and delete tests.
            bookingId = bookingid;

            // Attach created booking details to Playwright report.
            await testInfo.attach('created-booking', {
                body: JSON.stringify({ bookingid, booking }, null, 2),
                contentType: 'application/json',
            });
        });
    });

    // ============================================================
    // UPDATE BOOKING
    // ============================================================

    test('update the booking (token comes from the fixture)', async ({
        bookingApi,
        bookerToken,
    }, testInfo) => {

        await test.step('PUT /booking/{id} with the fixture token', async () => {

            // Update existing booking using token from fixture.
            log.info(`Step 1: updating booking ${bookingId} using fixture token`);

            const updated = await bookingApi.updateBooking(
                bookingId,

                // Create updated booking payload.
                buildBooking({
                    firstname: 'E2E',
                    lastname: 'Updated',
                    totalprice: 950
                }),

                // Authentication token generated by fixture.
                bookerToken,
            );

            // Verify lastname was updated.
            expect(updated.lastname).toBe('Updated');

            // Verify price was updated.
            expect(updated.totalprice).toBe(950);

            // Attach updated booking to report.
            await testInfo.attach('updated-booking', {
                body: JSON.stringify(updated, null, 2),
                contentType: 'application/json',
            });
        });

        await test.step('GET /booking/{id} to confirm the change persisted', async () => {

            // GET booking again to verify update was actually saved.
            log.info(`Step 2: reading booking ${bookingId} back to verify persistence`);

            const fetched = await bookingApi.getBooking(bookingId);

            // Verify updated value is persisted in database/API.
            expect(fetched.lastname).toBe('Updated');

            log.info(`Step 2: booking ${bookingId} confirmed as "Updated"`);
        });
    });

    // ============================================================
    // DELETE BOOKING
    // ============================================================

    test('delete the booking and confirm it is gone', async ({ bookingApi, bookerToken }) => {

        await test.step('DELETE /booking/{id} with the fixture token', async () => {

            // Delete booking using fixture token.
            log.info(`Step 1: deleting booking ${bookingId}`);

            // Booker returns 201 Created on successful DELETE.
            const status = await bookingApi.deleteBooking(bookingId, bookerToken);

            // Log DELETE response status.
            log.info(`Step 1: DELETE responded with status ${status}`);

            // Verify successful DELETE.
            expect(status).toBe(201);
        });

        await test.step('GET /booking/{id} should now 404', async () => {

            // Try to GET deleted booking.
            log.info(`Step 2: confirming booking ${bookingId} is gone (expect 404)`);

            const ghost = await bookingApi.getBookingResponse(bookingId);

            // Verify deleted booking returns 404.
            expect(ghost.status()).toBe(404);

            log.info(`Step 2: booking ${bookingId} returns 404 as expected`);
        });
    });

});